using System;

namespace AutoEntityGenerator.CodeGenerator
{
    internal abstract class CodeGenerator
    {
        public string TypeParameters { get; set; }
        public string GenericConstraints { get; set; }
        public string Properties { get; set; }
        protected string Comments =>
    $@"/*
    Generated by {nameof(AutoEntityGenerator)} on {DateTime.Now}
    For more information about {nameof(AutoEntityGenerator)}, Visit https://github.com/Peled-Zohar/AutoEntityCreator
*/
";
    }
}
